version: '2'

services:
  plex-proxy:

    image: nginx:1.15.2-alpine
    container_name: plex-proxy
    restart: always
    privileged: true

    network_mode: host
    #ports:
    #  - 22500:22500

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
