version: "2"

services:
  tvhproxy:
    image: thejf/antennas
    container_name: tvheadend-proxy
    privileged: true
    restart: always
    # network_mode: bridge
    ports:
      - 5004:5004

    volumes:
      - /etc/localtime:/etc/localtime:ro

    environment:
      - TVH_URL=http://localhost:9981
      - TUNER_COUNT=2
      - TVHEADEND_URL=http://gatz:Wordpass12@localhost:9981
      - ANTENNAS_URL=http://localhost:5004
